name = "solar-tavaoneedu"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# KV id: fill in after running: npx wrangler kv namespace create SOLAR_CACHE

[[d1_databases]]
binding = "DB"
database_name = "solar-history"
database_id = "2a7b5600-3362-421e-94ff-23f5cee5c2c4"

[[kv_namespaces]]
binding = "SOLAR_CACHE"
id = "87c78f7686db4af2a323e5fd604ec3ff"

[vars]
VAPID_PUBLIC_KEY = "BPx6rZBD1vl7h3x4LWXPwysmLOaX7Xa75SscME7b3LMIA5tyUFigrdhaSrRxRdJpTGciB8KkxoTdJgQmAE3zkSk"
